#!/bin/bash

record_screen() {
	sleep 0.2

	folder="${HOME}/media/rec/$(date +"%y-%m")"
	file="rec-$(date +"%F_%T")"

	avipath="${folder}/${file}.avi"
	mp4path="${folder}/${file}.mp4"

	mkdir -p "$folder"

	ffcast -s rec -m 2 "$avipath"

	ffmpeg -i "$avipath" "$mp4path" && rm "$avipath"

	echo $mp4path
}

kill_recording() {
	pkill -fxn '(/\S+)*ffmpeg\s.*\sx11grab\s.*'
	killall ffcast
	killall xrectsel
}

usage() {
    cat <<EOF
yoinkscreen v0.1
Usage:
  ${0##*/} [options]
Options:
  -h            print this help and exit
  -k            kill all running recording processes and exit (files will still be saved)
All options can be repeated, and are processed in order.
EOF
    exit "${1:-0}"
}

while getopts ":hk" arg; do
	case ${arg} in 
		h)
			usage
			exit 0
			;;
		k)
			kill_recording
			exit 0
			;;
		:)
			echo "$0: Must supply an argument to -$OPTARG." >&2
			exit 1
			;;
		?)
			echo "Invalid option: -${OPTARG}."
			exit 2
			;;
	esac
done

if pgrep -x "ffcast" >/dev/null
then
	kill_recording	
else
	record_screen
fi

