#!/bin/bash

sleep 0.2

FOLDER="${HOME}/media/rec/$(date +"%y-%m")"
FILE="rec-$(date +"%F_%T")"

AVIPATH="${FOLDER}/${FILE}.avi"
MP4PATH="${FOLDER}/${FILE}.mp4"

mkdir -p "$FOLDER"

st -c "yoinkscreen" -e ffcast -s rec -m 2 "$AVIPATH"

ffmpeg -i "$AVIPATH" "$MP4PATH" && rm "$AVIPATH"

echo $MP4PATH
